baseURL = "https://zhangtianyuan120220.github.io/Sky_distant-s-Blog/"
locale = "zh-cn"
defaultContentLanguage = "zh"
title = "Sky_distant's Blog"
theme = "stack"

[params]
  [params.colorScheme]
    enabled = true
    default = "auto"

[params.sidebar]
  avatar = "/img/avatar.png"
  subtitle = "ACM / 算法竞赛笔记记录"

[outputs]
  home = [ "HTML", "JSON" ]
  page = [ "HTML" ]
  section = [ "HTML" ]