baseURL = "https://zhangtianyuan120220.github.io/Sky_distant-s-Blog/"
languageCode = "zh-cn"
title = "Sky_distant's Blog"
theme = "stack"

buildFuture = true
buildDrafts = true

[params]
  [params.colorScheme]
    enabled = true
    default = "auto"

[params.sidebar]
  avatar = "/img/avatar.png"
  subtitle = "ACM / 算法竞赛笔记记录"

[outputs]
  home = [ "HTML", "JSON" ]
  page = [ "HTML" ]
  section = [ "HTML" ]

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "index"
  isPlainText = true